// This file will be auto-generated by Supabase CLI
// Run: npm run supabase:generate-types
// For now, we'll define basic types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          role: 'coach' | 'admin' | 'student'
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          role?: 'coach' | 'admin' | 'student'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          role?: 'coach' | 'admin' | 'student'
          created_at?: string
          updated_at?: string
        }
      }
      students: {
        Row: {
          id: string
          coach_id: string | null
          name: string
          rank: string
          avatar: string | null
          notes: string | null
          session_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          coach_id?: string | null
          name: string
          rank?: string
          avatar?: string | null
          notes?: string | null
          session_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          coach_id?: string | null
          name?: string
          rank?: string
          avatar?: string | null
          notes?: string | null
          session_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      lesson_plans: {
        Row: {
          id: string
          student_id: string
          name: string
          description: string | null
          lesson_ids: string[]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          student_id: string
          name: string
          description?: string | null
          lesson_ids?: string[]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          student_id?: string
          name?: string
          description?: string | null
          lesson_ids?: string[]
          created_at?: string
          updated_at?: string
        }
      }
      student_progress: {
        Row: {
          id: string
          student_id: string
          lesson_id: string
          slice_id: string
          step_number: number
          completed: boolean
          confidence: number
          importance: 'standard' | 'important' | 'critical'
          next_action: 'Teach' | 'Review' | 'Reteach' | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          student_id: string
          lesson_id: string
          slice_id: string
          step_number: number
          completed?: boolean
          confidence?: number
          importance?: 'standard' | 'important' | 'critical'
          next_action?: 'Teach' | 'Review' | 'Reteach' | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          student_id?: string
          lesson_id?: string
          slice_id?: string
          step_number?: number
          completed?: boolean
          confidence?: number
          importance?: 'standard' | 'important' | 'critical'
          next_action?: 'Teach' | 'Review' | 'Reteach' | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      // Add other tables as needed
    }
    Views: {
      student_summary: {
        Row: {
          id: string
          coach_id: string | null
          name: string
          rank: string
          avatar: string | null
          session_count: number
          created_at: string
          updated_at: string
          plan_id: string | null
          plan_name: string | null
          lessons_started: number
          avg_confidence: number
          steps_completed: number
          total_steps: number
        }
      }
    }
    Functions: {}
    Enums: {}
  }
}
